### ISSUE TITLE
Where i can found this book?

### ISSUE THREAD

**Issue by DAZLDAZLOW** [Apress/pro-c-sharp-10#1]

**Comment by jennifer-reusser** [comment]
Amazon is currently indicating the book is scheduled to be released in early September 2022.

**Comment by skimedic** [comment]
According to my editor, it's due to a terrible backlog in the print industry. I don't have any more information than that, unfortunately. it's a mystery what happens between when I turn everything in and it becomes a printed book.

**Comment by DAZLDAZLOW** [comment]
Thank you for information and thank you for your work. I am learning programming with Pro C#9 now, its very helpful book.
